dragonfly/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage import views as homepage

urlpatterns = [
    #url(r'^index/', 'homepage.views.index'),
    url(r'^$', homepage.index, name="homepage"),
    url(r'^logout/$', homepage.logoutUser, name="logout"),
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^records/',include('records.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^testapp/', include('testapp.urls')),
]

records/urls.py
from django.conf.urls import url
from . import views

app_name = 'records'
urlpatterns = [
    url(r'^gatunekac/$', views.GatunekAutocomplete.as_view(), name='gatunekac'),
    #url(r'^view/(?P<recordId>[0-9]+)', views.viewRecord, name="viewRecord"),
    url(r'^main/$', views.homeRecords, name='homeRecords' ),
    url(r'^new/$', views.RecordAdd.as_view(), name='addRecord'),
    url(r'^view/(?P<pk>[0-9]+)', views.RecordDetailView.as_view(), name="viewRecord"),
    url(r'^browse/$', views.RecordListView.as_view(), name='browseRecords' ),
    url(r'^edit/(?P<recordId>[0-9]+)', views.editRecord, name='editRecord'),
]

users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name='users'
urlpatterns = [
    url(r'^create/$', views.createUser, name='createUser' ),
    url(r'^login/$', views.loginUser, name='loginUser'),
    ]

records/models.py
from __future__ import unicode_literals

from django.db import models
from users.models import UserProfile
from django.contrib.auth.models import User
import datetime

class Gatunek(models.Model):
    nazwa_pl=models.CharField(max_length=128)
    nazwa_la=models.CharField(max_length=128)

    def  __str__(self):
        return self.nazwa_pl

class Record(models.Model):
    HABITAT_CHOICES = (
        ('FO','las'),
        ('ZA','zadrzewienie'),
        ('LA','łąka'),
        ('PO','pole'),
        ('NI','nieużytek'),
        ('TZ','teren zurbanizowany'),
        ('RZ','rzeka'),
        ('ZW','zbiornik wodny'),
        ('MO','wybrzeże morskie'),
    )
    BEHAVIOUR_CHOICES = (
        ('ST','stacjonarny'),
        ('PR','przelotny'),
        ('KO','koczujący'),
    )
    record_data = models.DateField()
    entry_data = models.DateField(auto_now_add=True) #
    author = models.ForeignKey(User)
    species = models.ForeignKey(Gatunek)
    notes = models.CharField(blank=True,null=True,max_length=500,default='')
    habitat = models.CharField(choices = HABITAT_CHOICES,max_length=20)
    behaviour = models.CharField(choices = BEHAVIOUR_CHOICES,max_length=20)
    county = models.CharField(max_length=50)
    place = models.CharField(max_length=50)
    num_individuals = models.IntegerField()
    num_adults = models.IntegerField(blank=True,null=True,default=0)
    num_juveniles = models.IntegerField(blank=True,null=True,default=0)
    num_males = models.IntegerField(blank=True,null=True,default=0)
    num_females = models.IntegerField(blank=True,null=True,default=0)


    def __str__(self):
        return ""+self.record_data.strftime("%Y,%m,%d")+","+self.species+","+str(self.num_individuals)+","+self.author

records/views.py
from users.models import User
from django.http import JsonResponse
from .models import Record,Gatunek
from records.models import UserProfile
from django import forms
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.http import Http404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from dal import autocomplete
from django.views.generic import ListView,DetailView
from django.views.generic import CreateView,UpdateView


from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime


def homeRecords(request):
    return render(request,'records/homeRecords.html')


@login_required
def addRecord(request):
    error=False
    if request.POST:
        form = addRecordForm(request.POST)
        if form.is_valid():
            record_data=form.cleaned_data['record_data']
            species = form.cleaned_data['species']
            notes = form.cleaned_data['notes']
            habitat = form.cleaned_data['habitat']
            behaviour = form.cleaned_data['behaviour']
            county = form.cleaned_data['county']
            place = form.cleaned_data['place']
            num_individuals = form.cleaned_data['num_individuals']
            num_adults = form.cleaned_data['num_adults']
            num_juveniles = form.cleaned_data['num_juveniles']
            num_males = form.cleaned_data['num_males']
            num_females = form.cleaned_data['num_females']
            new_record = Record(author=request.user,record_data=record_data,species=species,notes=notes,habitat=habitat,behaviour=behaviour,county=county,place=place,num_individuals=num_individuals,num_adults=num_adults,num_juveniles=num_juveniles,num_males=num_males,num_females=num_females)
            new_record.save()
            messages.success(request, 'Pomyślnie dodano nowy rekord')
            return render(request,'records/addRecord.html',{'form':form,})
        else:
            messages.error(request,'wystąpiły błędy')
            return render(request,'records/addRecord.html',{'form':form,})

    else:
        form = addRecordForm
        return render(request,'records/addRecord.html',{'form': form})

class addRecordForm(forms.Form):
    record_data = forms.DateField(label="Data obserwacji",initial=datetime.date.today,input_formats=["%d.%m.%Y","%d/%m/%Y"],widget=forms.DateInput(format="%d.%m.%Y"))
    author = UserProfile.id #FIXME powinno byc pole formularza a nie od razu wartosc?
    species = forms.ModelChoiceField(queryset=Gatunek.objects.all(),widget=autocomplete.ModelSelect2(url='records:gatunekac'))
    #species = forms.CharField(label="Gatunek",max_length=50)
    notes = forms.CharField(label="Uwagi",widget=forms.Textarea,max_length=500,required=False)
    habitat = forms.ChoiceField(label="Siedlisko",choices=Record.HABITAT_CHOICES)
    behaviour = forms.ChoiceField(label="Zachowanie",choices=Record.BEHAVIOUR_CHOICES)
    county = forms.CharField(label="Powiat",max_length=50)
    place = forms.CharField(label="Miasto",max_length=50)
    num_individuals=forms.IntegerField(label="Łączna liczba osobników",min_value=1,max_value=100000)
    num_adults=forms.IntegerField(required=False,label="Liczba os. dorosłych")
    num_juveniles=forms.IntegerField(required=False,label="Liczba os. młodych")
    num_males=forms.IntegerField(required=False,label="Liczba samców")
    num_females=forms.IntegerField(required=False,label="liczba samic")

    def clean(self):
        cleaned_data = super(addRecordForm,self).clean()
        return self.cleaned_data

    def clean_record_data(self):
        record_data=self.cleaned_data['record_data']
        if not (datetime.date(2017,1,1) <= record_data <= datetime.date.today()):
            dzisiaj=datetime.date.today().strftime('%d.%m.%Y')
            raise forms.ValidationError("Data nie zawiera sie w przedziale 1.1.2017-"+dzisiaj)
        return record_data


@login_required
def editRecord(request,recordId):
    instance = get_object_or_404(Record, id=recordId)
    form=editRecordForm(request.POST or None, instance = instance)
    if form.is_valid():
        form.save()
        messages.success(request, 'Rekord zapisany')
        return redirect('records:browseRecords')
    return render(request,'records/editRecord.html', {'form':form,'recordId':recordId})


class editRecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = '__all__'

@login_required
def viewRecord(request,recordId):
    record = get_object_or_404(Record, id=recordId)
    record_author=record.author.username
    record_habitat=record.get_habitat_display()
    record_behaviour=record.get_behaviour_display()
    form=viewRecordForm(initial={'author':record_author,'habitat':record_habitat,'behaviour':record_behaviour},instance=record)
    return render(request,'records/viewRecord.html', {'form':form,})

class viewRecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['record_data','author','species','notes','habitat','behaviour','county','place','num_individuals','num_adults','num_juveniles','num_males','num_females']

    record_data = forms.DateField(label="Data obserwacji",disabled=True)
    author = forms.CharField(label="Autor obserwacji", disabled=True)
    species = forms.CharField(label="Gatunek",disabled=True)
    notes = forms.CharField(label="Uwagi",disabled=True)
    habitat = forms.CharField(label="Siedlisko",disabled=True)
    behaviour = forms.CharField(label="Zachowanie",disabled=True)
    county = forms.CharField(label="Powiat",disabled=True)
    place = forms.CharField(label="Miasto",disabled=True)
    num_individuals=forms.IntegerField(label="Łączna liczba osobników",disabled=True)
    num_adults=forms.IntegerField(label="Liczba os. dorosłych",disabled=True)
    num_juveniles=forms.IntegerField(label="Liczba os. młodych",disabled=True)
    num_males=forms.IntegerField(required=False,label="Liczba samców",disabled=True)
    num_females=forms.IntegerField(required=False,label="liczba samic",disabled=True)

@login_required
def browseRecords(request):
    context = {
        'record_list' : Record.objects.all()[:10]
    }
    return render(request, 'records/browseRecords.html',context)

class GatunekAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        qs = Gatunek.objects.all()

        if self.q:
            qs = qs.filter(nazwa_pl__istartswith=self.q)
        return qs

#----------------------------- class-based-views
class addRecordFormMeta(ModelForm):
    species = forms.ModelChoiceField(queryset=Gatunek.objects.all(),widget=autocomplete.ModelSelect2(url='records:gatunekac'))

    class Meta:
        model = Record
        fields = '__all__'
        exclude = ('author',)
        labels = {
            'record_data' : 'Data obserwacji',
            'species' : 'Gatunek',
            'notes' : 'Uwagi',
            'habitat' : 'Siedlisko',
            'behaviour' : 'Zachowanie',
            'county' : 'Powiat',
            'place' : 'Miejscowość',
            'num_individuals' : 'Liczba osobników',
            'num_adults' : 'Liczba os. dorosłych',
            'num_juveniles' : 'Liczba os. młodych',
            'num_males' : 'Liczba samców',
            'num_females' : 'Liczba samic'
        }

    def clean(self):
        cleaned_data = super(addRecordFormMeta,self).clean()
        return cleaned_data

    def clean_record_data(self):
        record_data=self.cleaned_data['record_data']
        if not (datetime.date(2017,1,1) <= record_data <= datetime.date.today()):
            dzisiaj=datetime.date.today().strftime('%d.%m.%Y')
            raise forms.ValidationError("Data nie zawiera sie w przedziale 1.1.2017-"+dzisiaj)
        return record_data

class RecordAdd(CreateView):
    model = Record
    template_name = 'records/addRecord2.html'
    form_class=addRecordFormMeta

    def post(self,request):
        form = addRecordFormMeta(request.POST or None)
        if form.is_valid():
            #marker_lat=form.cleaned_data['marker_lat']
            #marker_lng=form.cleaned_data['marker_lng']
            record_data=form.cleaned_data['record_data']
            species = form.cleaned_data['species']
            notes = form.cleaned_data['notes']
            habitat = form.cleaned_data['habitat']
            behaviour = form.cleaned_data['behaviour']
            county = form.cleaned_data['county']
            place = form.cleaned_data['place']
            num_individuals = form.cleaned_data['num_individuals']
            num_adults = form.cleaned_data['num_adults']
            num_juveniles = form.cleaned_data['num_juveniles']
            num_males = form.cleaned_data['num_males']
            num_females = form.cleaned_data['num_females']
            new_record = Record(author=self.request.user,record_data=record_data,species=species,notes=notes,habitat=habitat,behaviour=behaviour,county=county,place=place,num_individuals=num_individuals,num_adults=num_adults,num_juveniles=num_juveniles,num_males=num_males,num_females=num_females)
            new_record.save()
            messages.success(request, 'Pomyślnie dodano nowy rekord')
            #print(marker_lng,marker_lat)
            newForm = addRecordFormMeta(initial={'record_data': record_data,"notes" : "brak uwag",'habitat':habitat,'county':county,'place':place})
            return render(request,'records/addRecord2.html',{'form':newForm,})
        else:
            messages.error(request,'wystąpiły błędy')
            return render(request,'records/addRecord2.html',{'form':form,})
        #TODO: dodać przekierowanie na stronę nowego rekordu z częścią pól pouzupełnianych danym z poprzednio dodanego rekordu


class RecordDetailView(DetailView):

    model = Record
    template_name = 'records/viewRecord2.html'

records/templates/records/addRecord.html
{% load static %}
{% load leaflet_tags %}

<!DOCTYPE HTML>
<html>

<head>
    <title> Dragonfly </title>
    <!-- tutaj wstawimy zmienną django zawierającą stałą z nazwą serwisu, aby moc potem w latwy sposob podmieniac nazwe w wersjach wielojezykowych -->
    <meta name="description" content="website description" />
    <!-- zmienna django -->
    <meta name="keywords" content="website keywords, website keywords" />
    <!-- zmienna django -->
    <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
    <!-- zmienna django -->
    <link rel="stylesheet" type="text/css" href="/static/style.css" /> {% leaflet_js %} {% leaflet_css %}
</head>

<body>
    <div id="main">
        <!-- sekcja naglowkowa -->
        <div id="header">
            <div id="logo">
                <div id="logo_text">
                    <h1><a href="{% url 'homepage' %">Dragon<span class="logo_colour">fly</span></a></h1>
                    <h2>Kartoteka obserwacji przyrodniczych.</h2>
                </div>
            </div>
            <div id="menubar">
                <ul id="menu">
                    <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
                    <li><a href="{% url 'homepage'%}">Strona glowna</a></li>
                    <li class="selected"><a href="{% url 'records:homeRecords' %}">Kartoteka</a></li>
                    <li><a href="">Ustawienia</a></li>
                    <!-- link do ustawien profilu uzytkownika -->
                    <li><a href="{% url 'admin:index' %}">Panel administratora</a></li>
                    <li><a href="{% url 'admin:index' %}">Pomoc</a></li>
                    <!-- zmien docelową stronę -->
                </ul>
            </div>
        </div>

        <!-- sekcja glownego contentu -->
        <div id="site_content">

            <!-- sidebar -->

            <div class="sidebar">
                <!-- insert your sidebar items here -->
                <p><a href="{% url 'records:addRecord' %}">Dodaj rekord</a></p>
                <p><a href="{% url 'records:browseRecords' %}">Przeglądaj rekordy</a></p>
            </div>
<div>
    <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>
            <!-- main content -->

            <div id="content">
                <!-- insert the page content here -->
                {% if messages %} {% for message in messages %}
                <h2 style="text-align:center">{{ message}}</h2> {% endfor %} {% endif %}
                <h1>Uzupełnij formularz danymi obserwacji</h1>
                <form method="post" action="{% url 'records:addRecord' %}">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <p><input type="submit" value="Utwórz" /></p>
                </form>


                <script>
                    function map_init_basic(mapa, options) {
                        marker = new L.marker([50.7, 23.28], {
                            draggable: true
                        });
                        mapa.addLayer(marker);
                        mapa.on('click', onMapClick);

                        function onMapClick(e) {
                            console.log(e.latlng.toString());
                            document.getElementById("id_place").value = e.latlng.lat.toFixed(2);
                            mapa.removeLayer(marker);
                            marker = new L.marker(e.latlng, {
                                draggable: true
                            });
                            mapa.addLayer(marker);
                            mapa.panTo(e.latlng);
                        }

                        marker.on('dragend', function(event) {
                            mark = event.target;
                            var position = mark.getLatLng();
                            marker.setLatLng(new L.LatLng(position.lat, position.lng), {
                                draggable: true
                            });
                            mapa.panTo(new L.LatLng(position.lat, position.lng));
                            console.log(position.toString()) //FIXME: nie dziala prawidlowo po pierwszym utworzeniu nowego markera i probie jego dragowania
                        });
                    }
                </script>
                {% leaflet_map "mapa" callback="window.map_init_basic"%}
            </div>
        </div>


        <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

        {{ form.media }}
        <div id="content_footer"></div>
        <div id="footer">
            Copyright &copy; colour_green | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">Website templates</a>
        </div>
    </div>
</body>

</html>

records/templates/records/browseRecords.html
<!DOCTYPE HTML>
<html>

<head>
  <title> Dragonfly  </title> <!-- tutaj wstawimy zmienną django zawierającą stałą z nazwą serwisu, aby moc potem w latwy sposob podmieniac nazwe w wersjach wielojezykowych -->
  <meta name="description" content="website description" /> <!-- zmienna django -->
  <meta name="keywords" content="website keywords, website keywords" /> <!-- zmienna django -->
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" /> <!-- zmienna django -->
  <link rel="stylesheet" type="text/css" href="/static/style.css"  />
</head>

<body>
  <div id="main">

      <!-- sekcja naglowkowa -->

    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="{% url 'homepage' %">Dragon<span class="logo_colour">fly</span></a></h1>
          <h2>Kartoteka obserwacji przyrodniczych.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="{% url 'homepage'%}">Strona glowna</a></li>
          <li class="selected"><a href="{% url 'records:homeRecords' %}">Kartoteka</a></li>
          <li><a href="">Ustawienia</a></li>  <!-- link do ustawien profilu uzytkownika -->
            <li><a href="{% url 'admin:index' %}">Panel administratora</a></li>
            <li><a href="{% url 'admin:index' %}">Pomoc</a></li> <!-- zmien docelową stronę -->
        </ul>
      </div>
    </div>

      <!-- sekcja glownego contentu -->
    <div id="site_content">

        <!-- sidebar -->

      <div class="sidebar">
        <!-- insert your sidebar items here -->
        <p><a href="{% url "records:addRecord" %}">Dodaj rekord</a></p>
        <p><a href="{% url "records:browseRecords" %}">Przeglądaj rekordy</a></p>
      </div>

        <!-- main content -->

      <div id="content">
        <!-- insert the page content here -->
        <h1>Witaj na stronie kartoteki przyrodniczej</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquet malesuada feugiat. Curabitur fermentum bibendum nulla, non dictum ipsum tincidunt non. Quisque convallis pharetra tempor. Donec id pretium leo. Pellentesque luctus massa non elit viverra pellentesque. Cras vitae neque molestie, rhoncus ipsum sit amet, lobortis dui. Fusce in urna sem. Vivamus vehicula dignissim augue et scelerisque. Etiam quam nisi, molestie ac dolor in, tincidunt tincidunt arcu. Praesent sed justo finibus, fringilla velit quis, porta erat. Donec blandit metus ut arcu iaculis iaculis. Cras nec dolor fringilla justo ullamcorper auctor. Aliquam eget pretium velit. Morbi urna justo, pulvinar id lobortis in, aliquet placerat orci.</p>
        {% if messages %}
            {% for message in messages %}
            <h2 style="text-align:center">{{ message }}</h2>
            {% endfor %}
        {% endif %}
        <h2>Zawartość tabeli rekordów:</h2>
        <p>Łączna liczba rekordów w bazie: {{ record_list.count }}</p>
        <table style="width:100%; border-spacing:0;">
          <tr><th>Lp.</th><th>Gatunek</th><th>Data obserwacji</th><th>Autor</th><th>Siedlisko</th><th>Miejscowość</th><th>Liczba osobników</th><th>Szczegóły</th></tr>
          {% for record in object_list|slice:":10"  %}
          <tr><td>{{ forloop.counter }}<td>{{ record.species }}</td><td>{{ record.record_data }}</td><td>{{ record.author.username }}</td><td>{{ record.get_habitat_display }}</td><td>{{ record.place }}</td><td>{{ record.num_individuals }}</td><td><a href=" {% url 'records:editRecord' recordId=record.id %}">Szczegóły</a><td></tr>
          {% endfor %}
        </table>
      </div>
    </div>

      <!-- footer -->

    <div id="content_footer"></div>
    <div id="footer">
      Copyright &copy; colour_green | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">Website templates</a>
    </div>
  </div>

</body>
</html>

records/templates/records/browseRecords2.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/static/custom.css"  />
  </head>
  <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Dragonfly</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Strona glowna</a></li>
        <li><a href="#about">Kartoteka</a></li>
        <li><a href="#contact">Profil</a></li>
        <li><a href="#contact">Pomoc</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <div class="starter-template">
    <h1>Lista ostatnich rekordów:</h1>
    <br>
    {% if records_num == 0 %}
    <p> Brak rekordów w bazie </p>
    {% else %}
<div class="row">
    <table class="table">
        <tr><th>Lp.</th><th>Gatunek</th><th>Data obserwacji</th><th>Autor</th><th>Siedlisko</th><th>Miejscowość</th><th>Liczba os.</th><th>Szczegóły</th></tr>
        {% for record in object_list %}
        <tr><td>{{ forloop.counter }}<td>{{ record.species }}</td><td>{{ record.record_data }}</td><td>{{ record.author.username }}</td><td>{{ record.get_habitat_display }}</td><td>{{ record.place }}</td><td>{{ record.num_individuals }}</td><td><a href=" {% url 'records:viewRecord' pk=record.id %}"><span class="glyphicon glyphicon-list-alt"></span></a><td></tr>
        {% endfor %}
    </table>
</div>
    <p class="lead">Liczba wszystkich rekordów w bazie: {{ records_num }}.</p>
  </div>
{% endif %}
</div><!-- /.container -->
  </body>
</html>

records/templates/records/editRecord.html
<!DOCTYPE HTML>
<html>

<head>
  <title> Dragonfly  </title> <!-- tutaj wstawimy zmienną django zawierającą stałą z nazwą serwisu, aby moc potem w latwy sposob podmieniac nazwe w wersjach wielojezykowych -->
  <meta name="description" content="website description" /> <!-- zmienna django -->
  <meta name="keywords" content="website keywords, website keywords" /> <!-- zmienna django -->
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" /> <!-- zmienna django -->
  <link rel="stylesheet" type="text/css" href="/static/style.css"  />
</head>

<body>
  <div id="main">
      <!-- sekcja naglowkowa -->
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="{% url 'homepage' %">Dragon<span class="logo_colour">fly</span></a></h1>
          <h2>Kartoteka obserwacji przyrodniczych.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="{% url 'homepage'%}">Strona glowna</a></li>
          <li class="selected"><a href="{% url 'records:homeRecords' %}">Kartoteka</a></li>
          <li><a href="">Ustawienia</a></li>  <!-- link do ustawien profilu uzytkownika -->
            <li><a href="{% url 'admin:index' %}">Panel administratora</a></li>
            <li><a href="{% url 'admin:index' %}">Pomoc</a></li> <!-- zmien docelową stronę -->
        </ul>
      </div>
    </div>

      <!-- sekcja glownego contentu -->
    <div id="site_content">

        <!-- sidebar -->

      <div class="sidebar">
        <!-- insert your sidebar items here -->
        <p><a href="{% url "records:addRecord" %}">Dodaj rekord</a></p>
        <p><a href="{% url "records:browseRecords" %}">Przeglądaj rekordy</a></p>
      </div>

        <!-- main content -->

      <div id="content">
        <!-- insert the page content here -->
        <h1>Witaj na stronie kartoteki przyrodniczej</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquet malesuada feugiat. Curabitur fermentum bibendum nulla, non dictum ipsum tincidunt non. Quisque convallis pharetra tempor. Donec id pretium leo. Pellentesque luctus massa non elit viverra pellentesque. Cras vitae neque molestie, rhoncus ipsum sit amet, lobortis dui. Fusce in urna sem. Vivamus vehicula dignissim augue et scelerisque. Etiam quam nisi, molestie ac dolor in, tincidunt tincidunt arcu. Praesent sed justo finibus, fringilla velit quis, porta erat. Donec blandit metus ut arcu iaculis iaculis. Cras nec dolor fringilla justo ullamcorper auctor. Aliquam eget pretium velit. Morbi urna justo, pulvinar id lobortis in, aliquet placerat orci.</p>

        <h2>Szczegóły rekordu:</h2>
        {% if messages %}
            {% for message in messages %}
            <h2 style="text-align:center">{{ message }}</h2>
            {% endfor %}
        {% else %}
        <form method="post" action="{% url "records:editRecord" recordId=recordId %}" >
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <p><input type="submit" value="Zapisz" /></p>
          </form>
         {% endif %}
      </div>
    </div>

      <!-- footer -->

    <div id="content_footer"></div>
    <div id="footer">
      Copyright &copy; colour_green | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">Website templates</a>
    </div>
  </div>

</body>
</html>