dragonfly/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage import views as homepage

urlpatterns = [
    #url(r'^index/', 'homepage.views.index'),
    url(r'^$', homepage.index, name="homepage"),
    url(r'^logout/$', homepage.logoutUser, name="logout"),
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^records/',include('records.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^testapp/', include('testapp.urls')),
]

records/urls.py
from django.conf.urls import url
from . import views

app_name = 'records'
urlpatterns = [
    url(r'^gatunekac/$', views.GatunekAutocomplete.as_view(), name='gatunekac'),
    #url(r'^view/(?P<recordId>[0-9]+)', views.viewRecord, name="viewRecord"),
    url(r'^main/$', views.homeRecords, name='homeRecords' ),
    url(r'^new/$', views.RecordAdd.as_view(), name='addRecord'),
    url(r'^view/(?P<pk>[0-9]+)', views.RecordDetailView.as_view(), name="viewRecord"),
    url(r'^browse/$', views.RecordListView.as_view(), name='browseRecords' ),
    url(r'^edit/(?P<recordId>[0-9]+)', views.editRecord, name='editRecord'),
]

users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name='users'
urlpatterns = [
    url(r'^create/$', views.createUser, name='createUser' ),
    url(r'^login/$', views.loginUser, name='loginUser'),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user_auth = models.OneToOneField(User, models.CASCADE)
    location = models.TextField(max_length=100, blank=True)
    registration_date = models.DateField(verbose_name="Data rejestracji")
    last_connected = models.DateTimeField(verbose_name="Data ostatniego logowania", null=True, default=None, blank=True)

    def __str__(self):
        return self.user_auth.username

users/views.py
from django.shortcuts import render,redirect
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
#from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms
from django.http import HttpResponseRedirect
from django.http import HttpResponse
import datetime

# Create your views here.
def loginUser(request):
    if request.POST:
        form = Form_login_user(request.POST) # a co jesli bys utworzyl forma bez request.posta jak ponizej?
        if form.is_valid():
            username = form.cleaned_data['user_name']
            password = form.cleaned_data['user_password']
            user = authenticate(username=username,password=password)
            if user: #mozna tez: if user is not None
                login(request, user)
                return HttpResponseRedirect('udalo sie zalogowac, gratulacje')
            else:
                return HttpResponse('nie udalo sie zalogowac')
        else:
            return HttpRespons('formularze niepoprawnie zwalidowany')

            #wykombinuj bardziej ambitne rozwiazanie
            #render(request,'users/loginUser', {'message' : 'login error'})
        #moje kombinowane rozwiazanie niedokonczone z powodu natkniecia sie na dokumentacji metody login() i wygodniejszego rozwiazania zaprezentowanego w https://docs.djangoproject.com/en/1.10/topics/auth/default/
        #user_name = form.cleaned_data['user_name']
        # user_password = form.cleaned_data['user_password']
        # try:
        #     user = User.objects.get(username=user_name) # za duzo mieszasz z nazewnictwem zmiennych, ujednolic to
        # except User.DoesNotExist:
        #     raise forms.ValidationError('bledna nazwa uzytkownika')
        # if(user.password == user_password):
        #     #autoryzacja
        # else:
        #     forms.ValidationError('bledne haslo')


    else:
        form = Form_login_user()
        return render(request,'users/loginUser.html', {'form' : form })

def createUser(request):
    if request.POST:
        form = Form_add_user(request.POST)
        if form.is_valid():
                username = form.cleaned_data['username']
                name = form.cleaned_data['name']
                surname = form.cleaned_data['surname']
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                new_user = User.objects.create_user(username = username,first_name = name,last_name = surname, email = email, password=password)
                new_user.is_active = True
                new_user.last_name = name
                new_user.save()
                new_UserProfile=UserProfile(user_auth=new_user,registration_date=datetime.datetime.now().strftime("%Y-%m-%d"))
                new_UserProfile.save()
                messages.success(request, 'Pomyślnie utworzono nowego użytkownika,mozesz sie zalogować')
                return render(request,'users/createUser.html', {'form' : form})
                #nie bedziemy na razie bawic sie w funkcje reverse
                #return HttpResponseRedirect(reverse('public_empty'))
        else:
            return render(request,'users/createUser.html', {'form' : form})
    else:
        form = Form_add_user()
        return render(request,'users/createUser.html', {'form' : form})

class Form_login_user(forms.Form):
    user_name = forms.CharField(label="username",max_length=30)
    user_password = forms.CharField(label="password")

class Form_add_user(forms.Form):
    name = forms.CharField(label="Imie",max_length=30)
    surname = forms.CharField(label="Nazwisko",max_length=30 )
    username = forms.CharField(label="Login",max_length=30)
    email = forms.EmailField(label="Email",max_length=30)
    password = forms.CharField(label="haslo", widget=forms.PasswordInput,max_length=30)
    password_bis = forms.CharField(label="Powtorz haslo", widget=forms.PasswordInput,max_length=30)
    def clean(self):
        cleaned_data= super (Form_add_user, self).clean()
        password = self.cleaned_data.get('password')
        password_bis = self.cleaned_data.get('password_bis')
        if(password != password_bis):
            raise forms.ValidationError('hasla nie sa identyczne')
        return self.cleaned_data

users/templates/users/createUser.html
<!DOCTYPE HTML>
<html>

<head>
  <title> Dragonfly  </title> <!-- tutaj wstawimy zmienną django zawierającą stałą z nazwą serwisu, aby moc potem w latwy sposob podmieniac nazwe w wersjach wielojezykowych -->
  <meta name="description" content="website description" /> <!-- zmienna django -->
  <meta name="keywords" content="website keywords, website keywords" /> <!-- zmienna django -->
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" /> <!-- zmienna django -->
  <link rel="stylesheet" type="text/css" href="/static/style.css"  />
</head>

<body>
  <div id="main">

      <!-- sekcja naglowkowa -->

    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="{% url 'homepage' %">Dragon<span class="logo_colour">fly</span></a></h1>
          <h2>Kartoteka obserwacji przyrodniczych.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="{% url 'homepage'%}">Strona glowna</a></li>
          <li><a href="{% url 'records:homeRecords' %}">Kartoteka</a></li>
          <li><a href="">Ustawienia</a></li>  <!-- link do ustawien profilu uzytkownika -->
            <li><a href="{% url 'admin:index' %}">Panel administratora</a></li>
            <li><a href="{% url 'admin:index' %}">Pomoc</a></li> <!-- zmien docelową stronę -->
        </ul>
    </div>
  </div>
      <!-- {% block main_content %} {% endblock %} -->
      <!-- sekcja glownego contentu -->
    <div id="site_content">
      <div>
        {% if messages %}
            {% for message in messages %}
            <h2 style="text-align:center">{{ message }}</h2>
            {% endfor %}
        {% else %}
        <h1 style="text-align:center">Uzupełnij dane:</h1>
        <div id="register">
        <form method="post" action="{% url "users:createUser" %}" >
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <p><input type="submit" value="Create" /></p>
          </form>
        </div>
        {% endif %}
      </div>
    </div>

      <!-- footer -->

    <div id="content_footer"></div>
    <div id="footer">
      Copyright &copy; colour_green | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">Website templates</a>
    </div>
  </div>

</body>
</html>

users/templates/users/loginUser.html
<html>
<head>
  <style>
    div {
      margin:auto;
      width: 15%;
      border: 3px solid black;
      padding: 20px;
    }
  </style>
</head>

  <body>
    <div>
      <form method="post" action="{% url "users:loginUser" %}" >
              {% csrf_token %}
              <!-- This line inserts a CSRF token. -->
              <table>
                  {{ form.as_table }}
                  <!-- This line displays lines of the form. -->
              </table>
              <p><input type="submit" value="Login" /></p>
      </form>
    </div>
  </body>

</html>